print ("Sheriena S. Lastica")
print ("Tapuyan, Gasan, Marinduque")
print ("August 29, 2001")
print ("Marinduque State College")
print ("BS/it - 2F")
print ("------- My Hobbies -------")
print ("drawing")
print ("singing")
print ("watching tv")
print ("listening to music")
print ("dancing")